version: '3.8'

services:
  master1:
    image: mariadb:11.4
    container_name: master1
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root123
    networks:
      - dbnet

  master2:
    image: mariadb:11.4
    container_name: master2
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root123
    networks:
      - dbnet

  maxscale:
    image: mariadb/maxscale:latest
    container_name: maxscale
    ports:
      - "4000:4000"
      - "8989:8989"
    volumes:
      - ./maxscale.cnf:/etc/maxscale.cnf
    depends_on:
      - master1
      - master2
    networks:
      - dbnet

networks:
  dbnet:
    driver: bridge
